### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by hansheng0512** [BGU-CS-VIL/DeepDPM#3]
Hi, may I know what's the steps if I want to train using my own dataset?

**Comment by meitarronen** [comment]
Sure.

DeepDPM is designed to work on features. However, if your data is relatively low dimensional you might try both (training on raw data and on embeddings).  While it can operate on higher dimensional data, we recommended data in a max dimension of 128D. 

To train DeepDPM on embeddings:
1. Apply feature extraction to get lower dimensional embeddings of your data.
Depending on your data you can choose your feature extractor. In our work, for high dimensional data we used the deep unsupervised feature extractor, MoCo (but there are also other options. Of course you can train it on your data or use pretrained weights). For smaller datasets we used UMAP on the raw data or an Autoencoder followed by a UMAP. See our supplementary material for details.
2. Given low dimensional representations, save these embeddings into pt files using torch.save.
3. Use/create a similar class of embedded datasets like the one in  src/embedded_datasets class to load your data.

Training on the raw data:
1. You would need to create a dataset class for your custom dataset. See e.g. the classes we have under src/datasets. You could extend the My Dataset class for easier implementation. Note that other classes that extend it read the (raw) data and create a TensorDataset out of it (one for training and one for val/testing). 

For both options, you would also need to add the name of the dataset to the argument options in the main run file in order to choose it.

Good luck!
