### ISSUE TITLE
Model weights for inference code

### ISSUE THREAD

**Issue by kurianbenoy-sentient** [BGU-CS-VIL/DeepDPM#36]
For loading a pretrained model from a saved checkpoint, and for an inference example, see: scripts\DeepDPM_load_from_checkpoint.py.

What an example weights provided in the repository which can be used for inference?

I noticed the AE encoder weights doesn't contain the layer:

```
cp_state['state_dict']['cluster_net.class_fc2.weight'].shape[0] 
```

Can the authors of this project provide the sample model weights which can be used for checking the capability of this clustering algorithm?

**Comment by meitarronen** [comment]
Hey @kurianbenoy-sentient,
we are sorry we currently cannot upload our model weights.
The weights saved in the repository are for used the feature extraction only (i.e., the weights of the AE).

In order to replicate the results reported in the paper, please follow the instructions on the readme file.
